baseURL = "https://edoardodebenedetti.me"
languageCode = "en-us"
title = "Edoardo Debenedetti"
tags = ["portfolio", "web design", "blog", "develpment"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true

[Params]
    tagline = "Student, Junior Entrepreneur, Tech Enthusiast"
    author = "Edoardo Debenedetti"
    description = "Computer Engineering Student @ PoliTo (Turin), exchanging @ TongjiU (Shanghai), Junior Entrepreneur @ JEToP."
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = ""
    opengraphImage = "/images/osprey.png"
    twitter = "edoardo_debe"
    linkedin = "edoardo-debenedetti"
    github = "dedeswim"
    facebook = ""
    email = "edoardo.m.debenedetti@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
# [[menu.main]]
#     name = "Work"
#     url  = "/#work"
#     weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
